### ISSUE TITLE
Add `finally`-style hooks that could be executed always

### ISSUE THREAD

**Issue by geaaru** [MottainaiCI/ssh-compose#5]
Considering that SSH Protocol limits the using of environment variables and a solution is to generate a file with envs to sync in the node could be good to have a specific hook type that define the commands to run also when something goes wrong.

For example:
```yaml
hooks:
- event: finally
  flags:
    - always_executed
  commands:
    - echo "cleanup temporary files"
```
